### ISSUE TITLE
[TODO list] All things we have to add/improve

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#42]
- [ ] Add the simple split op (not the split_v) which permits to split a tensor in 'n' parts along 'axis'.
- [ ] Support the front-end test case : squeeze(input) with intput.shape = [1,1,1,1] (in that case, shape is not defined into the TF graph for the output node.
- [ ] Improve Front-end test coverage (more cases)
- [ ] Improve Back-end test coverage (more cases) 
- [ ] Add front end support for convolution (@tjingrant)

**Comment by tjingrant** [comment]
Since this is a community to-do list, I'll edit to add my task here as well!

**Comment by akurniawan** [comment]
It seems no one looking at https://github.com/onnx/onnx-tensorflow/issues/38? From my point of view this is one useful feature that we can have. onnx-caffe2 has a simple command line to convert onnx model to caffe2 so it can be loaded from caffe2 environment directly, as shown [here](https://github.com/onnx/tutorials/blob/master/tutorials/OnnxCaffe2Import.ipynb)

**Comment by tjingrant** [comment]
It's more or less a duplicate of https://github.com/onnx/onnx-tensorflow/issues/44.

Since getting the model proto is basically everything one needs to serve the model.
I could write up a tutorial in about a week or so.

**Comment by lysukhin** [comment]
Is there a way to export `onnx-tf` model as frozen graph for inference in, for example, C++?

**Comment by chinhuang007** [comment]
Close since no activities for more than a year. Please reopen if anyone wants to continue the discussions.
