### ISSUE TITLE
Support operations from onnx opset 11

### ISSUE THREAD

**Issue by iiSeymour** [onnx/onnx-tensorflow#449]
Support the following operators introduce in opset 11:

- [ ] `ONNX_OPERATOR_SET_SCHEMA_CLASS_NAME(Onnx, 11, Loop);`
- [ ] `ONNX_OPERATOR_SET_SCHEMA_CLASS_NAME(Onnx, 11, Round);`
- [ ] `ONNX_OPERATOR_SET_SCHEMA_CLASS_NAME(Onnx, 11, BitShift);`

**Comment by chinhuang007** [comment]
The latest list is (with owner or PR#):
Loop
Unique
CumSum
Round
BitShift
TopK (Winnie)
DepthToSpace (Chin)
Equal (https://github.com/onnx/onnx-tensorflow/pull/466)

**Comment by chinhuang007** [comment]
The following is the list of new or updated opts in the released ONNX 1.6, opset 11. We will start tracking the

Loop
BitShift
Unique
CumSum
Round
TopK
DepthToSpace
Equal
Constant
DynamicQuantizeLinear
GatherElements
ScatterElements
Scatter
Clip
Resize
Range
Det
ScatterND
GatherND
Gather
OneHot
Slice
Squeeze
Unsqueeze
Flatten
ArgMin
ArgMax
ReduceL1
ReduceL2
ReduceLogSum
ReduceLogSumExp
ReduceMax
ReduceMean
ReduceProd
ReduceSum
ReduceSumSquare
Compress
Concat
Hardmax
LogSoftmax
Softmax
Scan
Split
AveragePool
MaxPool
MaxUnpool
LpPool
Conv
ConvTranspose
SequenceEmpty
SequenceConstruct
SequenceInsert
SequenceAt
SequenceErase
SequenceLength
SplitToSequence
ConcatFromSequence
Pad
Gemm
If
NonMaxSuppression

**Comment by winnietsang** [comment]
Here is the current status of supported Opset 11 ops in our master branch.

**TODO List:(23/62)**
Loop
BitShift
Unique
CumSum
DynamicQuantizeLinear
GatherElements
Clip
Resize
Det
Gather
LpPool
Conv
ConvTranspose
SequenceEmpty
SequenceConstruct
SequenceInsert
SequenceAt
SequenceErase
SequenceLength
SplitToSequence
ConcatFromSequence
Gemm
If

**Completed List:(39/62)**
Round
TopK
DepthToSpace
Equal
Constant
ScatterElements
Scatter
Range
ScatterND
GatherND
OneHot
Slice
Squeeze
Unsqueeze
Flatten
ArgMin
ArgMax
ReduceL1
ReduceL2
ReduceLogSum
ReduceLogSumExp
ReduceMax
ReduceMean
ReduceProd
ReduceSum
ReduceSumSquare
Compress
Concat
Hardmax
LogSoftmax
Softmax
Scan
Split
AveragePool
MaxPool
MaxUnpool
Pad
NonMaxSuppression

**Comment by cmosquer** [comment]
aad

**Comment by cmosquer** [comment]
Hello, I wanted to know if there has been any updates on these. Some days ago I buildt onnx-tensorflow from source with opset 11 but stil I get a NotImplementedError on a Gather operation. I see it is in the TODO list, just wanted to motivate on this issue!!

**Comment by winnietsang** [comment]
@cmosquer PR #537 will add the support for Opset 11 Gather operator

**Comment by chinhuang007** [comment]
Updates on the todo list:

Loop
BitShift (open PR https://github.com/onnx/onnx-tensorflow/pull/563)
Unique
CumSum
DynamicQuantizeLinear
GatherElements
Resize
Det (open PR https://github.com/onnx/onnx-tensorflow/pull/564)
Gather
LpPool
Conv
ConvTranspose
SequenceEmpty (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SequenceConstruct  (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SequenceInsert  (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SequenceAt (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SequenceErase  (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SequenceLength  (open PR https://github.com/onnx/onnx-tensorflow/pull/560)
SplitToSequence
ConcatFromSequence
If

**Comment by chinhuang007** [comment]
Updates on the todo list:

Loop
Unique
CumSum
DynamicQuantizeLinear (https://github.com/onnx/onnx-tensorflow/pull/568)
GatherElements
Resize
Gather
LpPool
Conv
ConvTranspose
SplitToSequence
ConcatFromSequence
If

**Comment by hope-yao** [comment]
Hi @chinhuang007 , thank you for the information and work on this excellent repo. Could you please let me know if you can add Resize to opset 11 soon? I got stuck here... Thanks a lot.

**Comment by chinhuang007** [comment]
@hope-yao Resize has been looked at. ONNX has a lot of attributes for resize op. Some variations are fairly complicated and hard to understand. We will try to get back to it as soon as we can.

**Comment by winnietsang** [comment]
Updates on the todo list:

Loop (#592)
Unique
CumSum (#575)
GatherElements
Resize
Gather
LpPool
ConvTranspose
SplitToSequence
ConcatFromSequence (#597) 
If

**Comment by ajmalrasi** [comment]
@chinhuang007 @winnietsang  add support for Resize, SSD needs Resize. convertion from pytorch model to onnx fails.

**Comment by ajmalrasi** [comment]
add support for Resize, SSD needs Resize op. i'm unable to load onnx file.
`NotImplementedError: Resize version 11 is not implemented.`

**Comment by ajmalrasi** [comment]
@chinhuang007 @winnietsang  add support for Resize, SSD needs Resize op. i'm unable to load onnx file.
`NotImplementedError: Resize version 11 is not implemented.`
